// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

namespace dreamCare.FhirApi.Aidbox.HL7_Fhir_R4_Core;

public class DomainResource : Resource
{
    public Narrative? Text { get; set; }
    public Resource[]? Contained { get; set; }
    public Extension[]? Extension { get; set; }
    public Extension[]? ModifierExtension { get; set; }
    
    public override string ToString() => 
        JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
    
}

