// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

namespace dreamCare.FhirApi.Aidbox.HL7_Fhir_R4_Core;

public class MedicinalProductManufactured : DomainResource
{
    public required CodeableConcept ManufacturedDoseForm { get; set; }
    public CodeableConcept? UnitOfPresentation { get; set; }
    public required Quantity Quantity { get; set; }
    public ResourceReference[]? Manufacturer { get; set; }
    public ResourceReference[]? Ingredient { get; set; }
    public ProdCharacteristic? PhysicalCharacteristics { get; set; }
    public CodeableConcept[]? OtherCharacteristics { get; set; }
    
    public override string ToString() => 
        JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
    
}

