// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

namespace dreamCare.FhirApi.Aidbox.HL7_Fhir_R4_Core;

public class MedicinalProductUndesirableEffect : DomainResource
{
    public ResourceReference[]? Subject { get; set; }
    public CodeableConcept? SymptomConditionEffect { get; set; }
    public CodeableConcept? Classification { get; set; }
    public CodeableConcept? FrequencyOfOccurrence { get; set; }
    public Population[]? Population { get; set; }
    
    public override string ToString() => 
        JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
    
}

