// WARNING: This file is autogenerated by FHIR Schema Codegen.
// https://github.com/fhir-schema/fhir-schema-codegen
// Any manual changes made to this file may be overwritten.

namespace dreamCare.FhirApi.Aidbox.HL7_Fhir_R4_Core;

public class Resource 
{
    public string? Id { get; set; }
    public Meta? Meta { get; set; }
    public string? ImplicitRules { get; set; }
    public string? Language { get; set; }
    
    public override string ToString() => 
        JsonSerializer.Serialize(this, Aidbox.Config.JsonSerializerOptions);
    
}

