name: dreamcare_ehr_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.0
  intl: ^0.20.2
  google_fonts: ^6.2.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_riverpod: ^3.0.0-dev.16
  riverpod_annotation: ^3.0.0-dev.16
  cached_network_image: ^3.4.1
  transparent_image: ^2.0.1
  go_router: ^16.0.0
  font_awesome_flutter: ^10.8.0
  flutter_secure_storage: ^9.2.4
  fhir_r4: ^0.4.2
  aad_b2c_webview: ^0.1.2
  logging: ^1.3.0
  connectivity_plus: ^6.1.4
  mocktail: ^1.0.4
  http: ^1.4.0
  fhir_r4_at_rest: ^0.4.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  riverpod_generator: ^3.0.0-dev.16
  riverpod_lint: ^3.0.0-dev.16
  test: ^1.25.15
  build_verify: ^3.1.1

flutter:
  uses-material-design: true
